kumuluzee:
  name: searcher-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
  metrics:
    web-instrumentation:
      - name: searcher-endpoint
        url-pattern: /v1/searcher/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="0174a08c-8d63-4e43-a5b3-855e2865241e-ls.logit.io" port="18985" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'

rest-properties:
  maintenance-mode: false
  broken: false
external-api:
  distanceapi: http://www.mapquestapi.com/directions/v2/routematrix?key=RfVAdKJ87CU9OIZBm4GWGBLkVkHv8E7b